index:
    path: /
    controller: App\Controller\DefaultController::index

users:
    path: /users
    controller: App\Controller\TeacherController::users

courses:
    path: /courses/{userId}
    controller: App\Controller\CourseController::courses

login:
    path: /login

logout:
    path: /logout