index:
    path: /
    controller: App\Controller\DefaultController::index

users:
    path: /users
    controller: App\Controller\TeacherController::users

#Courses
courses:
    path: /courses
    controller: App\Controller\CourseController::courses

#End Courses

#Questions

questions:
    path: /courses/questions/{courseId}
    controller: App\Controller\QuestionController:questions

newQuestionForm:
    path: /courses/question/new
    controller: App\Controller\QuestionController:viewQuestion


addQuestion:
    path: /courses/question/add/{courseId}
    controller: App\Controller\QuestionController::addQuestion

updateQuestion:
    path: /courses/questions/edit/{questionId}/success
    controller: App\Controller\QuestionController::updateQuestion
    requirements:
        id: '\d+'

viewQuestion:
    path: /courses/questions/edit/{questionId}/view
    controller: App\Controller\QuestionController::viewQuestion
    requirements:
        id: '\d+'

#End Questions

#Answer

answers:
    path: /courses/questions/answers/{questionId}
    controller: App\Controller\AnswerController::answers

newAnswerForm:
  path: /courses/questions/answers/new
  controller: App\Controller\AnswerController:viewAnswer


addAnswer:
  path: /courses/questions/answers/add/{questionId}
  controller: App\Controller\AnswerController::addAnswer

updateAnswer:
  path: /courses/questions/answers/edit/{answerId}/success
  controller: App\Controller\AnswerController::updateAnswer
  requirements:
    id: '\d+'

correctAnswerExist:
  path: /courses/questions/answers/edit/{answerId}/exist
  controller: App\Controller\AnswerController::correctAnswerExist
  requirements:
    id: '\d+'

viewAnswer:
  path: /courses/questions/answers/edit/{answerId}/view
  controller: App\Controller\AnswerController::viewAnswer
  requirements:
    id: '\d+'

#End Answer

#Exams
exams:
    path: /courses/exams/{courseId}
    controller: App\Controller\ExamController::exams

studentsPublish:
    path: /courses/exams/students/{examId}
    controller: App\Controller\ExamController::students

examResults:
    path: /courses/exams/students/results/{examId}
    controller: App\Controller\ExamController::examResults

publishAll:
    path: /courses/exams/students/publishAll/
    controller: App\Controller\ExamController::publishAll

publishExam:
    path: /courses/exams/students/publish/{examId}/{studentId}
    controller: App\Controller\ExamController::publishExam

editExam:
    path: /courses/exams/edit/{examId}
    controller: App\Controller\ExamController::editExam

deleteExam:
    path: /courses/exams/delete/{examId}
    controller: App\Controller\ExamController::deleteExam

takeExam:
    path: /courses/exams/take/{instanceId}
    controller: App\Controller\ExamController::takeExam

completeExam:
    path: /courses/exams/complete
    controller: App\Controller\ExamController::completeExam
    methods: [POST]

result:
      path: /courses/exams/result/{instanceId}
      controller: App\Controller\ExamController::result

#End Exams

#Students
students:
    path: /students/
    controller: App\Controller\StudentController::students
#End Students

login:
    path: /login

logout:
    path: /logout