index:
    path: /
    controller: App\Controller\DefaultController::index

users:
    path: /users
    controller: App\Controller\TeacherController::users

#Courses
courses:
    path: /courses
    controller: App\Controller\CourseController::courses

#End Courses

#Questions

questions:
    path: /courses/questions/{courseId}
    controller: App\Controller\QuestionController:questions

newQuestionForm:
    path: /courses/question/new
    controller: App\Controller\QuestionController:viewQuestion


addQuestion:
    path: /courses/question/add/{courseId}
    controller: App\Controller\QuestionController::addQuestion

updateQuestion:
    path: /courses/questions/edit/{questionId}/success
    controller: App\Controller\QuestionController::updateQuestion
    requirements:
        id: '\d+'

questionAddNew:
    path: /courses/questions/add/addNew
    controller: App\Controller\QuestionController::questionAddNew

viewQuestion:
    path: /courses/questions/edit/{questionId}/view
    controller: App\Controller\QuestionController::viewQuestion
    requirements:
        id: '\d+'

#End Questions

#Exams
exams:
    path: /courses/exams/{courseId}
    controller: App\Controller\ExamController::exams

examResults:
    path: /courses/exams/students/results/{examId}
    controller: App\Controller\ExamController::examResults

publishExam:
    path: /courses/exams/students/publish/{examId}/{studentId}
    controller: App\Controller\ExamController::publishExam

editExam:
    path: /courses/exams/edit/{examId}
    controller: App\Controller\ExamController::editExam

deleteExam:
    path: /courses/exams/delete/{examId}
    controller: App\Controller\ExamController::deleteExam

takeExam:
    path: /courses/exams/take/{instanceId}
    controller: App\Controller\ExamController::takeExam

completeExam:
    path: /complete
    controller: App\Controller\ExamController::completeExam
    methods: [POST]

result:
      path: /courses/exams/result/{instanceId}
      controller: App\Controller\ExamController::result

#End Exams

#Students
students:
    path: /students
    controller: App\Controller\StudentController::students
#End Students

login:
    path: /login

logout:
    path: /logout