index:
    path: /
    controller: App\Controller\DefaultController::index

users:
    path: /users
    controller: App\Controller\TeacherController::users

login:
    path: /login

logout:
    path: /logout