index:
    path: /
    controller: App\Controller\DefaultController::index

users:
    path: /users
    controller: App\Controller\TeacherController::users

#Courses
courses:
    path: /courses
    controller: App\Controller\CourseController::courses

#End Courses

#Questions

questions:
    path: /courses/questions/{courseId}
    controller: App\Controller\QuestionController:questions

editQuestion:
    path: /courses/questions/edit/{questionId}
    controller: App\Controller\QuestionController::editQuestion

#End Questions

#Exams
exams:
    path: /courses/exams/{courseId}
    controller: App\Controller\ExamController::exams

publishExam:
    path: /courses/exams/publish/{examId}
    controller: App\Controller\ExamController::publishExam

editExam:
    path: /courses/exams/edit/{examId}
    controller: App\Controller\ExamController::editExam

deleteExam:
    path: /courses/exams/delete/{examId}
    controller: App\Controller\ExamController::deleteExam

#Testing
takeExam:
    path: /courses/exams/take/{examId}
    controller: App\Controller\ExamController::takeExam

completeExam:
    path: /complete
    controller: App\Controller\ExamController::completeExam
    methods: [POST]

result:
      path: /courses/exams/result/{instanceId}
      controller: App\Controller\ExamController::result

#End Testing
#End Exams

#Students
students:
    path: /students
    controller: App\Controller\StudentController::students
#End Students

login:
    path: /login

logout:
    path: /logout